server: 
  port: 8000
  
spring:
  application:
    name: Api-gateway
    
  cloud:
    gateway:
      routes:
      - id: admin-service
        uri: http://localhost:8005
        predicates:
        - Path=/admin/**
      - id: user-service
        uri: http://localhost:8001
        predicates:
        - Path=/users/**
      - id: payment-service
        uri:  http://localhost:8004
        predicates:
        - Path=/payment/** 
      - id: login-service
        uri:  http://localhost:8001
        predicates:
        - Path=/login/**
      - id: ticket-reservation-service
        uri:  http://localhost:8003
        predicates:
        - Path=/ticketreservation/**
      - id: train-service
        uri:  http://localhost:8002
        predicates:
        - Path=/train/**        
        
  eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
    hostname: localhost
